export const ActionTypes = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SIGN_UP: "SIGN_UP",
  
  HAS_USER_MODAL:'HAS_USER_MODAL',
  NOT_AVAILABLE_MODAL:'NOT_AVAILABLE_MODAL',
  SUCCESS_SIGNUP_MODAL:'SUCCESS_SIGNUP_MODAL',
  SUCCESS_LOGIN_MODAL:'SUCCESS_LOGIN_MODAL',
  FAIL_LOGIN_MODAL:'FAIL_LOGIN_MODAL',

 
};
